version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
  api:
    build: .
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: energydb
      DB_USER: energy
      DB_PASS: energy
      JWT_SECRET: 3b75fbfddbe2695c4ddc7f494ac2d4dfc7b8355a5e62398dd7aab4f54acf0045
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: npm run start
    restart: unless-stopped
volumes:
  db_data:



